name: deploy

on:
  push:
    branches: [ master ]

jobs:
  update-files:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Update Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          port: ${{secrets.PORT}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/DoEasyMoney
            git reset --hard origin/master
            git pull

  build-client:
    if: "contains(github.event.commits[0].message, '[need build client]')"
    timeout-minutes: 2
    needs: [update-files]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Client
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          port: ${{secrets.PORT}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/DoEasyMoney/client
            git reset --hard origin/master
            git pull
  deploy-server:
    if: "contains(github.event.commits[0].message, '[need deploy server]')"
    needs: [ update-files ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          port: ${{secrets.PORT}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/DoEasyMoney/api
            npm install
            pm2 restart api